apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- digest: sha256:e963a1c2ec6964b673e8c698738adfff92fc78c2b911b10d98bcb0b4a0a42336
  name: controller
  newName: 274565299670.dkr.ecr.us-west-2.amazonaws.com/pcc-operator
