apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- digest: sha256:82bda76e54c7717f2b90be9c19ecaa9b6d301b72ab6b2edf6002ce4399e640ff
  name: controller
  newName: docker.io/aakatev/pcc-operator
