apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- digest: sha256:3906b9d7f1eafb94bcc95c7a2c035b3e0af6917993243344429ef6971d932bd5
  name: controller
  newName: 274565299670.dkr.ecr.us-west-2.amazonaws.com/pcc-operator
