apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- digest: sha256:a5c6bcc65e29d1c93f39cc0c8f89983a68806e3abaffe993fdf6ce2f692ec0c4
  name: controller
  newName: 274565299670.dkr.ecr.us-west-2.amazonaws.com/pcc-operator
