apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- digest: sha256:0b15904db4b66375351f5e667386ce2ff422cfef21cbd6e3e76342a6e3c747f4
  name: controller
  newName: 274565299670.dkr.ecr.us-west-2.amazonaws.com/pcc-operator
