apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- digest: sha256:89fa57b530aae5b49dbc94e5064cf2c046a45d014989b5a8a057d1d177dced6d
  name: controller
  newName: 274565299670.dkr.ecr.us-west-2.amazonaws.com/pcc-operator
